title: Hamish Ivison
description: >-
  Hamish's site.
baseurl: ""
url: "https://hamishivi.github.io"


# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll/scholar

remote_theme: jekyll/minima@41b97699af658128fa9983e5312ca5516641f335
markdown: kramdown
tags:
minima:
  skin: dark
  social_links:
    twitter: hamishivi
    github: hamishivi
    linkedin: hamish-ivison-6a17a1118

scholar:
  style: _bibliography/association-for-computational-linguistics.csl.txt
  bibliography_template: bibtemplate
  bibliography_list_tag: div
  bibliography_item_tag: ul
