#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Hamish Ivison
tagline:             'Developer, Student, Classics Nerd'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             '/about'
paginate:            5

# About/contact
author:
  name:              Hamish Ivison
  url:               hamishivi.github.io
  email:             hamishivi@gmail.com

# Custom vars
version:             1.0.0
